image: node:10.16.3

stages:
  - deploy

deploy:
  image: ubuntu:18.04
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
  script:
    - lftp -e "open adress.test user $FTP_USERNAME $FTP_PASSWORD mirror bye"
